import type { GraphStats, ConnectorInfo, SearchResult, GraphData, ActivityEvent } from './api';

export const mockGraphStats: GraphStats = {
  nodeCount: 247,
  edgeCount: 612,
  staleness: 3.2,
  lastSync: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  healthScore: 94,
  nodesByLabel: {
    LogicalService: 28,
    Repository: 45,
    Deployment: 36,
    RuntimeService: 22,
    Team: 12,
    Person: 68,
    Pipeline: 18,
    Monitor: 18,
  },
};

export const mockConnectors: ConnectorInfo[] = [
  {
    id: 'github-1',
    name: 'GitHub',
    type: 'github',
    status: 'healthy',
    lastSync: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    entityCount: 142,
    nextSync: new Date(Date.now() + 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'k8s-1',
    name: 'Kubernetes',
    type: 'kubernetes',
    status: 'healthy',
    lastSync: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    entityCount: 89,
    nextSync: new Date(Date.now() + 55 * 60 * 1000).toISOString(),
  },
  {
    id: 'datadog-1',
    name: 'Datadog',
    type: 'datadog',
    status: 'degraded',
    lastSync: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
    entityCount: 34,
    nextSync: null,
  },
  {
    id: 'backstage-1',
    name: 'Backstage',
    type: 'backstage',
    status: 'not_connected',
    lastSync: null,
    entityCount: 0,
    nextSync: null,
  },
  {
    id: 'jira-1',
    name: 'Jira',
    type: 'jira',
    status: 'not_connected',
    lastSync: null,
    entityCount: 0,
    nextSync: null,
  },
  {
    id: 'idp-1',
    name: 'Identity Provider',
    type: 'identity',
    status: 'not_connected',
    lastSync: null,
    entityCount: 0,
    nextSync: null,
  },
];

export const mockSearchResults: SearchResult[] = [
  { id: '1', name: 'payments-service', label: 'LogicalService', canonicalId: 'svc:payments-service', owner: 'payments-team', lastSynced: new Date().toISOString() },
  { id: '2', name: 'payments-api', label: 'Repository', canonicalId: 'repo:org/payments-api', owner: 'payments-team', lastSynced: new Date().toISOString() },
  { id: '3', name: 'auth-service', label: 'LogicalService', canonicalId: 'svc:auth-service', owner: 'platform-team', lastSynced: new Date().toISOString() },
  { id: '4', name: 'user-service', label: 'LogicalService', canonicalId: 'svc:user-service', owner: 'identity-team', lastSynced: new Date().toISOString() },
  { id: '5', name: 'api-gateway', label: 'RuntimeService', canonicalId: 'rt:api-gateway-prod', owner: 'platform-team', lastSynced: new Date().toISOString() },
  { id: '6', name: 'payments-deploy-prod', label: 'Deployment', canonicalId: 'deploy:payments-prod', owner: 'payments-team', lastSynced: new Date().toISOString() },
  { id: '7', name: 'checkout-pipeline', label: 'Pipeline', canonicalId: 'pipe:checkout-ci', owner: 'payments-team', lastSynced: new Date().toISOString() },
  { id: '8', name: 'payments-monitor', label: 'Monitor', canonicalId: 'mon:payments-latency', owner: 'sre-team', lastSynced: new Date().toISOString() },
];

export const mockGraphData: GraphData = {
  nodes: [
    { data: { id: '1', label: 'LogicalService', name: 'payments-service', type: 'LogicalService', tier: 1, owner: 'payments-team', environment: 'production' } },
    { data: { id: '2', label: 'Repository', name: 'payments-api', type: 'Repository', owner: 'payments-team', environment: 'production' } },
    { data: { id: '3', label: 'LogicalService', name: 'auth-service', type: 'LogicalService', tier: 1, owner: 'platform-team', environment: 'production' } },
    { data: { id: '4', label: 'LogicalService', name: 'user-service', type: 'LogicalService', tier: 2, owner: 'identity-team', environment: 'production' } },
    { data: { id: '5', label: 'RuntimeService', name: 'api-gateway', type: 'RuntimeService', tier: 1, owner: 'platform-team', environment: 'production' } },
    { data: { id: '6', label: 'Deployment', name: 'payments-deploy-prod', type: 'Deployment', owner: 'payments-team', environment: 'production' } },
    { data: { id: '7', label: 'Pipeline', name: 'checkout-pipeline', type: 'Pipeline', owner: 'payments-team', environment: 'production' } },
    { data: { id: '8', label: 'Monitor', name: 'payments-monitor', type: 'Monitor', owner: 'sre-team', environment: 'production' } },
    { data: { id: '9', label: 'Team', name: 'payments-team', type: 'Team' } },
    { data: { id: '10', label: 'Team', name: 'platform-team', type: 'Team' } },
    { data: { id: '11', label: 'Person', name: 'Alice Chen', type: 'Person' } },
    { data: { id: '12', label: 'Person', name: 'Bob Smith', type: 'Person' } },
    { data: { id: '13', label: 'Deployment', name: 'auth-deploy-prod', type: 'Deployment', owner: 'platform-team', environment: 'production' } },
    { data: { id: '14', label: 'Repository', name: 'auth-service-repo', type: 'Repository', owner: 'platform-team', environment: 'production' } },
    { data: { id: '15', label: 'LogicalService', name: 'notification-service', type: 'LogicalService', tier: 2, owner: 'comms-team', environment: 'production' } },
    { data: { id: '16', label: 'Deployment', name: 'user-deploy-prod', type: 'Deployment', owner: 'identity-team', environment: 'staging' } },
  ],
  edges: [
    { data: { id: 'e1', source: '1', target: '3', type: 'DEPENDS_ON' } },
    { data: { id: 'e2', source: '1', target: '4', type: 'CALLS' } },
    { data: { id: 'e3', source: '2', target: '1', type: 'IMPLEMENTS' } },
    { data: { id: 'e4', source: '5', target: '1', type: 'ROUTES_TO' } },
    { data: { id: 'e5', source: '6', target: '1', type: 'DEPLOYS' } },
    { data: { id: 'e6', source: '7', target: '6', type: 'PRODUCES' } },
    { data: { id: 'e7', source: '8', target: '1', type: 'MONITORS' } },
    { data: { id: 'e8', source: '9', target: '1', type: 'OWNS' } },
    { data: { id: 'e9', source: '10', target: '3', type: 'OWNS' } },
    { data: { id: 'e10', source: '11', target: '9', type: 'MEMBER_OF' } },
    { data: { id: 'e11', source: '12', target: '10', type: 'MEMBER_OF' } },
    { data: { id: 'e12', source: '13', target: '3', type: 'DEPLOYS' } },
    { data: { id: 'e13', source: '14', target: '3', type: 'IMPLEMENTS' } },
    { data: { id: 'e14', source: '3', target: '4', type: 'DEPENDS_ON' } },
    { data: { id: 'e15', source: '1', target: '15', type: 'CALLS' } },
    { data: { id: 'e16', source: '16', target: '4', type: 'DEPLOYS' } },
    { data: { id: 'e17', source: '5', target: '3', type: 'ROUTES_TO' } },
  ],
};

export const mockActivity: ActivityEvent[] = [
  { id: '1', type: 'sync', message: 'GitHub connector synced 142 entities', connector: 'GitHub', timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString() },
  { id: '2', type: 'sync', message: 'Kubernetes connector synced 89 entities', connector: 'Kubernetes', timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString() },
  { id: '3', type: 'merge', message: 'Merged duplicate: payments-svc -> payments-service', timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString() },
  { id: '4', type: 'connector_added', message: 'Datadog connector configured', connector: 'Datadog', timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString() },
  { id: '5', type: 'sync', message: 'Datadog connector synced 34 monitors', connector: 'Datadog', timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString() },
  { id: '6', type: 'schema_change', message: 'Added RuntimeService.replicas property', timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString() },
  { id: '7', type: 'sync', message: 'GitHub connector synced 138 entities', connector: 'GitHub', timestamp: new Date(Date.now() - 5 * 3600 * 1000).toISOString() },
  { id: '8', type: 'merge', message: 'Merged duplicate: auth-svc -> auth-service', timestamp: new Date(Date.now() - 6 * 3600 * 1000).toISOString() },
  { id: '9', type: 'sync', message: 'Kubernetes connector synced 85 entities', connector: 'Kubernetes', timestamp: new Date(Date.now() - 7 * 3600 * 1000).toISOString() },
  { id: '10', type: 'connector_added', message: 'GitHub connector configured', connector: 'GitHub', timestamp: new Date(Date.now() - 24 * 3600 * 1000).toISOString() },
];
